### ISSUE TITLE
作者你好，shellserver.dex 这个文件，我在resource目录 里并没有找到。可以帮忙看看吗？

### ISSUE THREAD

**Issue by woeinsd** [yanglikai0806/testool#2]
通过app_process命令执行shell。先通过adb shell进入设备的shell，再输入命令：nohup app_process -Djava.class.path=/sdcard/autotest/shellserver.dex /system/bin --nice-name=shellServer shellService.Main > /dev/null 2>&1 & ，最后执行exit退出shell。
（确保/sdcard/autotest/shellserver.dex文件存在，若不存在需从resource目录下手动push到设备中）

**Comment by yanglikai0806** [comment]
你好，，文件已经提交到resource目录下了。
